name: Build APK

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install cython==0.29.36
        pip install buildozer

    - name: Validate buildozer.spec
      run: |
        echo "Checking for duplicate sections..."
        if [ $(grep -c "\[app\]" buildozer.spec) -ne 1 ]; then
          echo "Error: Duplicate [app] sections found in buildozer.spec"
          exit 1
        fi
        if [ $(grep -A1 "^\[app\]" buildozer.spec | grep -c "requirements") -ne 1 ]; then
          echo "Error: Duplicate requirements found in buildozer.spec"
          exit 1
        fi

    - name: Build APK
      run: |
        buildozer init
        buildozer -v android debug

    - name: Find APK file
      run: |
        echo "APK file location:"
        find . -name "*.apk" -exec ls -lh {} \;
        echo "Copying APK to bin directory..."
        mkdir -p bin
        find . -name "*.apk" -exec cp {} bin/ \;

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: photogallery-app
        path: bin/*.apk
