name: Build APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install buildozer

    - name: Build APK
      run: |
        buildozer -v android debug
        ls -l bin/

    - name: Upload APK
      uses: actions/upload-artifact@v4  # ⚠️ تأكد من أنك تستخدم v4
      with:
        name: photogallery-app
        path: |
          bin/*.apk
          *.apk
          .buildozer/android/platform/build-*/dists/*/build/outputs/apk/debug/*.apk
